common: &common
  adapter: postgresql
  host: localhost
  pool: 5
  encoding: unicode

development:
  <<: *common
  database: ceres_development
  username: jathayde
  password:

test:
  <<: *common
  database: ceres_test
  username: jathayde
  password:

production:
  <<: *common
  database: ceres
  username:
  password:
